# Generated by Django 4.0.4 on 2022-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='vacancy',
            field=models.IntegerField(default=7),
        ),
    ]
