# Generated by Django 4.0.4 on 2022-06-01 17:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_guide_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='myImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
