# Generated by Django 4.0.4 on 2022-06-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_guide_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
