# Generated by Django 4.0.4 on 2022-06-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_guide_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='myImage',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
