# Generated by Django 4.0.4 on 2022-06-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_guide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
