# Generated by Django 4.0.4 on 2022-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_guide_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='domain_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='domain_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='domain_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
