# Generated by Django 4.0.4 on 2022-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='s_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
