# Generated by Django 4.0.4 on 2022-06-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_guide_domain_1_alter_guide_domain_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_domain', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('no_of_members', models.IntegerField()),
                ('reg_no_1', models.IntegerField()),
                ('student_1_name', models.CharField(max_length=100)),
                ('student_1_email', models.CharField(max_length=100)),
                ('student_1_no', models.BigIntegerField()),
                ('reg_no_2', models.IntegerField()),
                ('student_2_name', models.CharField(max_length=100)),
                ('student_2_email', models.CharField(max_length=100)),
                ('student_2_no', models.BigIntegerField()),
            ],
        ),
    ]
