# Generated by Django 4.0.4 on 2022-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_guide_s_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='s_no',
        ),
        migrations.AlterField(
            model_name='guide',
            name='serial_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
