# Generated by Django 4.0.4 on 2022-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='reg_no_2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_2_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_2_no',
            field=models.BigIntegerField(blank=True),
        ),
    ]
