# Generated by Django 4.0.4 on 2022-06-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_team_reg_no_2_alter_team_student_2_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='no_of_members',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=10),
        ),
    ]
