# Generated by Django 4.0.4 on 2022-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_guide_s_no_alter_guide_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
