# Generated by Django 4.0.4 on 2022-06-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_team_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='experience',
        ),
    ]
