# Generated by Django 4.0.4 on 2022-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_team_no_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='no_of_members',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
    ]
