# Generated by Django 4.0.4 on 2022-06-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_guide_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
