# Generated by Django 4.0.4 on 2022-06-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_guide_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='guide',
            field=models.ManyToManyField(blank=True, null=True, to='pages.guide'),
        ),
    ]
