# Generated by Django 4.0.4 on 2022-06-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_team_reg_no_2_alter_team_student_2_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
