# Generated by Django 4.0.4 on 2022-06-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_team_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='guide',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='pages.guide'),
        ),
    ]
