# Generated by Django 4.0.4 on 2022-06-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_team_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='guide',
        ),
        migrations.AddField(
            model_name='team',
            name='guide',
            field=models.ManyToManyField(blank=True, null=True, to='pages.guide'),
        ),
    ]
