# Generated by Django 4.0.4 on 2022-06-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_team_guide_team_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='guide',
            field=models.ManyToManyField(blank=True, to='pages.guide'),
        ),
    ]
