# Generated by Django 4.0.4 on 2022-06-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_team_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='guide',
        ),
        migrations.AddField(
            model_name='team',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.guide'),
        ),
    ]
