# Generated by Django 4.0.4 on 2022-06-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_otp_two_alter_team_teamid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(default='CSE', max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_domain', models.CharField(max_length=100)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('no_of_members', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10)),
                ('reg_no_1', models.BigIntegerField()),
                ('student_1_name', models.CharField(max_length=100)),
                ('student_1_email', models.CharField(max_length=100)),
                ('student_1_no', models.BigIntegerField()),
                ('reg_no_2', models.BigIntegerField(blank=True, null=True)),
                ('student_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_2_email', models.CharField(blank=True, max_length=100, null=True)),
                ('student_2_no', models.BigIntegerField(blank=True, null=True)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.guide')),
            ],
        ),
    ]
