# Generated by Django 4.0.4 on 2022-07-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_temp_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='guide_email',
            field=models.CharField(default='email@gmail.com', max_length=100),
        ),
    ]
