# Generated by Django 4.0.4 on 2022-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_team_guide_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='guide',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
