# Generated by Django 4.0.4 on 2022-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_team_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
