# Generated by Django 4.0.4 on 2022-07-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_temp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_team',
            name='reg_no_3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp_team',
            name='student_3_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temp_team',
            name='student_3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temp_team',
            name='student_3_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
