# Generated by Django 4.0.4 on 2022-10-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_temp_team_guide_temp_team_reg_no_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='reg_no_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='student_3_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='student_3_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='student_3_no',
        ),
    ]
