# Generated by Django 4.0.4 on 2022-10-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_remove_team_reg_no_3_remove_team_student_3_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_team',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='temp_team',
            name='reg_no_3',
        ),
        migrations.RemoveField(
            model_name='temp_team',
            name='student_3_email',
        ),
        migrations.RemoveField(
            model_name='temp_team',
            name='student_3_name',
        ),
        migrations.RemoveField(
            model_name='temp_team',
            name='student_3_no',
        ),
    ]
