# Generated by Django 4.0.4 on 2022-10-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_remove_temp_team_guide_remove_temp_team_reg_no_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
