# Generated by Django 4.0.4 on 2023-01-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_alter_guide_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_1_email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
