# Generated by Django 4.0.4 on 2023-02-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_alter_team_guide_alter_team_guide_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='guide',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='guide_email',
            field=models.CharField(max_length=100),
        ),
    ]
